In [1]:

import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;
#reading data form CSV
df=pd.read_csv('Data.csv')

#forming different dataframes for independent and dependent and variable
X= df.iloc[:,:-1].values 
y=df.iloc[:,-1].values

In [2]:
#handling missing values
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(strategy='mean')

X[:,1:2]=imputer.fit_transform(X[:,1:2])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [3]:
#Encoding independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [4]:
#encoding dependent variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [6]:
#splitting train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2,random_state=1)

print(X_train,X_test,y_train,y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]] 
 [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]] [0 1 0 0 1 1 0 1] [0 1]


In [7]:
#feature scaling : Standardization and normalization
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0182239953527132]
 [0.0 1.0 0.0 -0.014117293757057777 nan]
 [1.0 0.0 0.0 0.566708506533324 0.583476671494251]
 [0.0 0.0 1.0 -0.30453019390224867 -0.2974586952715793]
 [0.0 0.0 1.0 -1.9018011447007988 -1.3385641287221062]
 [1.0 0.0 0.0 1.1475343068237058 1.1440719048906884]
 [0.0 1.0 0.0 1.4379472069688968 1.4644120382600814]
 [1.0 0.0 0.0 -0.7401495441200351 -0.537713795298624]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.8580539286680168]
 [1.0 0.0 0.0 -0.44973664397484414 0.18305150478250995]]
